name       : ruby-win32-file
version    : 0.8.2
release    : 1
source     :
    - https://rubygems.org/downloads/win32-file-0.8.2.gem : ac4089bd5a17f302f189c76fe16e1a6da45cfabf8d2af8fd66c92de77a16e252
license    : Artistic-2.0
component  : programming.ruby
summary    : RubyGem - win32-file
description: |
    Ruby library that extends the File class for MS Windows.
builddeps  :
    - pkgconfig(ruby-2.3)
rundeps    :
    - ruby-ffi
    - ruby-ffi-win32-extensions
    - ruby-win32-file-stat
install    : |
    %gem_install
